# Generated by Django 5.0 on 2024-01-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_alter_room_price_alter_room_rooms_alter_room_toilet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="toilet",
            new_name="toilets",
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=150),
        ),
    ]
