# Generated by Django 5.0 on 2024-01-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="kind",
            field=models.CharField(
                choices=[("rooms", "Rooms"), ("experiences", "Experiences")],
                max_length=15,
            ),
        ),
    ]
